camera0: 0
camera1: 0
frame_width: 640
frame_height: 490
mono_calibration_frames: 20
stereo_calibration_frames: 20
view_resize: 0.5
checkerboard_box_size_scale : 1.7
checkerboard_rows: 8
checkerboard_columns: 6
cooldown: 100
